import { GameSpecSchema, type GameSpec, type GameSpecInput } from './spec.js';

// Hand-written games. Used for "Quick Games", as few-shot examples for the
// brain, and as the offline fallback when a brain answer cannot be repaired.

const RAW: GameSpecInput[] = [
  {
    id: 'sky_toss',
    title: 'Sky Toss Showdown',
    one_line_rules: 'Throw the ball as high as you can. Three throws each. Highest throw wins.',
    mode: 'turn_battle',
    players: 2,
    min_players: 1,
    max_players: 8,
    turn_order: 'turns',
    rounds: 3,
    timer_s: 15,
    trackers: ['ball', 'person'],
    scoring: [{ event: 'ball_apex', measure: 'height_m', points: 'measure', once_per_turn: true }],
    fouls: [{ event: 'cross_line', condition: 'before ball_release', penalty: 'round_void' }],
    turn_end: [{ event: 'ball_catch' }, { event: 'ball_bounce' }, { event: 'ball_out_of_frame' }],
    aggregate: 'best',
    win_condition: 'highest',
    referee_style: 'football_announcer',
  },
  {
    id: 'bounce_catch',
    title: 'Bounce & Catch',
    one_line_rules: 'Bounce the ball and catch it. One point per catch. Thirty seconds each.',
    mode: 'turn_battle',
    players: 2,
    min_players: 1,
    max_players: 8,
    turn_order: 'turns',
    rounds: 2,
    timer_s: 30,
    trackers: ['ball', 'hands'],
    scoring: [{ event: 'ball_catch', measure: 'count', points: 1, condition: 'after ball_bounce' }],
    fouls: [{ event: 'ball_out_of_frame', penalty: 'end_turn' }],
    aggregate: 'sum',
    win_condition: 'highest',
    referee_style: 'football_announcer',
  },
  {
    id: 'keepy_uppy',
    title: 'Keepy-Uppy',
    one_line_rules: 'Keep the ball in the air with feet, knees or head. Every touch counts. Do not let it drop.',
    mode: 'turn_battle',
    players: 2,
    min_players: 1,
    max_players: 8,
    turn_order: 'turns',
    rounds: 2,
    timer_s: 60,
    trackers: ['ball', 'feet', 'head'],
    scoring: [{ event: 'ball_apex', measure: 'count', points: 1 }],
    turn_end: [{ event: 'ball_bounce' }, { event: 'ball_out_of_frame' }],
    aggregate: 'best',
    win_condition: 'highest',
    referee_style: 'football_announcer',
  },
  {
    id: 'target_toss',
    title: 'Target Toss',
    one_line_rules: 'Throw the ball into the goal. Three points per goal. Five throws each.',
    mode: 'turn_battle',
    players: 2,
    min_players: 1,
    max_players: 8,
    turn_order: 'turns',
    rounds: 5,
    timer_s: 15,
    trackers: ['ball', 'named_object'],
    targets: ['goal'],
    scoring: [{ event: 'ball_in_zone', target: 'goal', points: 3, once_per_turn: true }],
    fouls: [{ event: 'cross_line', condition: 'before ball_release', penalty: 'round_void' }],
    turn_end: [{ event: 'ball_in_zone', target: 'goal' }, { event: 'ball_bounce' }, { event: 'ball_out_of_frame' }],
    aggregate: 'sum',
    win_condition: 'highest',
    referee_style: 'football_announcer',
  },
  {
    id: 'long_throw',
    title: 'Long Throw',
    one_line_rules: 'Throw the ball as far as you can from behind the line. Longest throw wins.',
    mode: 'turn_battle',
    players: 2,
    min_players: 1,
    max_players: 8,
    turn_order: 'turns',
    rounds: 3,
    timer_s: 20,
    trackers: ['ball', 'person', 'zone'],
    scoring: [{ event: 'ball_bounce', measure: 'distance_m', points: 'measure', once_per_turn: true }],
    fouls: [{ event: 'cross_line', condition: 'before ball_release', penalty: 'round_void' }],
    turn_end: [{ event: 'ball_bounce' }],
    aggregate: 'best',
    win_condition: 'highest',
    referee_style: 'wrestling_hype',
  },
  {
    id: 'jump_battle',
    title: 'Jump Battle',
    one_line_rules: 'Jump as high as you can. Three jumps each. Highest jump wins.',
    mode: 'turn_battle',
    players: 2,
    min_players: 1,
    max_players: 8,
    turn_order: 'turns',
    rounds: 3,
    timer_s: 10,
    trackers: ['person', 'feet'],
    scoring: [{ event: 'jump', measure: 'height_m', points: 'measure', once_per_turn: true }],
    turn_end: [{ event: 'jump' }],
    aggregate: 'best',
    win_condition: 'highest',
    referee_style: 'wrestling_hype',
  },
  {
    id: 'freeze_statue',
    title: 'Freeze Tag Statue',
    one_line_rules: 'Dance until I shout FREEZE. Then be a statue. Too slow and you lose a life.',
    mode: 'duel',
    players: 3,
    min_players: 2,
    max_players: 6,
    turn_order: 'simultaneous',
    rounds: 5,
    lives: 3,
    timer_s: 10,
    trackers: ['person'],
    calls: { events: ['freeze'], every_s: 5, window_s: 4 },
    scoring: [{ event: 'freeze', points: 1, condition: 'is call', once_per_turn: true }],
    fouls: [{ event: 'timer_end', condition: 'no score', penalty: 'lose_life' }],
    aggregate: 'sum',
    win_condition: 'last_standing',
    referee_style: 'pirate',
  },
  {
    id: 'reaction_race',
    title: 'Reaction Race',
    one_line_rules: 'When I shout GO, throw your hands up. Fastest total time wins. No early starts!',
    mode: 'turn_battle',
    players: 2,
    min_players: 1,
    max_players: 8,
    turn_order: 'turns',
    rounds: 5,
    timer_s: 3,
    trackers: ['person', 'hands'],
    scoring: [{ event: 'hands_up', measure: 'reaction_ms', points: 'measure', once_per_turn: true }],
    fouls: [
      { event: 'hands_up', condition: 'reaction_ms < 100', penalty: 'points', points: 1000 },
      { event: 'timer_end', condition: 'no score', penalty: 'points', points: 3000 },
    ],
    turn_end: [{ event: 'hands_up' }],
    aggregate: 'sum',
    win_condition: 'lowest',
    referee_style: 'robot_ref',
  },
  {
    id: 'squat_storm',
    title: 'Squat Storm',
    one_line_rules: 'Do as many full squats as you can in thirty seconds. Most squats wins.',
    mode: 'duel',
    players: 2,
    min_players: 1,
    max_players: 4,
    turn_order: 'simultaneous',
    rounds: 1,
    timer_s: 30,
    trackers: ['person'],
    scoring: [{ event: 'squat', measure: 'count', points: 1 }],
    aggregate: 'sum',
    win_condition: 'highest',
    referee_style: 'calm_coach',
  },
  {
    id: 'mirror_me',
    title: 'Mirror Me',
    one_line_rules: 'Copy the move I call as fast as you can. Right move scores, wrong move loses a point.',
    mode: 'duel',
    players: 2,
    min_players: 1,
    max_players: 4,
    turn_order: 'simultaneous',
    rounds: 6,
    timer_s: 5,
    trackers: ['person', 'hands'],
    calls: { events: ['hands_up', 'squat', 'lean_left', 'lean_right', 'jump'], every_s: 1, window_s: 4 },
    scoring: [
      { event: 'hands_up', points: 1, condition: 'is call', once_per_turn: true },
      { event: 'squat', points: 1, condition: 'is call', once_per_turn: true },
      { event: 'lean_left', points: 1, condition: 'is call', once_per_turn: true },
      { event: 'lean_right', points: 1, condition: 'is call', once_per_turn: true },
      { event: 'jump', points: 1, condition: 'is call', once_per_turn: true },
    ],
    fouls: [
      { event: 'hands_up', condition: 'during call and not call', penalty: 'points', points: -1 },
      { event: 'squat', condition: 'during call and not call', penalty: 'points', points: -1 },
      { event: 'lean_left', condition: 'during call and not call', penalty: 'points', points: -1 },
      { event: 'lean_right', condition: 'during call and not call', penalty: 'points', points: -1 },
      { event: 'jump', condition: 'during call and not call', penalty: 'points', points: -1 },
    ],
    aggregate: 'sum',
    win_condition: 'highest',
    referee_style: 'robot_ref',
  },
  {
    id: 'sprint_tap',
    title: 'Sprint & Tap',
    one_line_rules: 'Run and touch the far marker, then sprint back and touch the home marker. Fastest wins.',
    mode: 'turn_battle',
    players: 2,
    min_players: 1,
    max_players: 8,
    turn_order: 'turns',
    rounds: 2,
    timer_s: 30,
    trackers: ['person', 'named_object'],
    targets: ['far', 'home'],
    scoring: [
      {
        event: 'touch_object',
        target: 'home',
        measure: 'duration_s',
        points: 'measure',
        condition: 'after touch_object:far',
        once_per_turn: true,
      },
    ],
    fouls: [{ event: 'timer_end', condition: 'no score', penalty: 'points', points: 60 }],
    turn_end: [{ event: 'touch_object', target: 'home', condition: 'has score' }],
    aggregate: 'best',
    win_condition: 'lowest',
    referee_style: 'football_announcer',
  },
  {
    id: 'boss_raid_basic',
    title: 'Boss Raid: Thunder Rock',
    one_line_rules: 'Jump, squat and punch to hurt the boss. When I shout FREEZE, stand still or lose a shield!',
    mode: 'boss_raid',
    players: 2,
    min_players: 1,
    max_players: 6,
    turn_order: 'simultaneous',
    rounds: 1,
    lives: 3,
    timer_s: 90,
    trackers: ['person'],
    calls: { events: ['freeze'], every_s: 15, window_s: 3 },
    boss: { name: 'Thunder Rock', hp: 150 },
    scoring: [
      { event: 'jump', points: 5, condition: 'not call' },
      { event: 'squat', points: 3, condition: 'not call' },
      { event: 'punch', points: 2, condition: 'not call' },
    ],
    fouls: [
      { event: 'jump', condition: 'during call', penalty: 'lose_life' },
      { event: 'squat', condition: 'during call', penalty: 'lose_life' },
      { event: 'punch', condition: 'during call', penalty: 'lose_life' },
    ],
    aggregate: 'sum',
    win_condition: 'co_op',
    referee_style: 'wrestling_hype',
  },
];

export const TEMPLATES: readonly GameSpec[] = RAW.map((raw) => {
  const r = GameSpecSchema.safeParse(raw);
  if (!r.success) throw new Error(`Template ${raw.id} is invalid: ${r.error.message}`);
  return r.data;
});

export function getTemplate(id: string): GameSpec | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
